apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: cowweb
  name: cowweblb
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "30"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: cowweb
  type: LoadBalancer
status:
  loadBalancer: {}
